### PR TITLE
Adding pickup, release and physics based collision sounds.

### PR DESCRIPTION
**Pull request by wmcnamara**
This PR adds code and sounds for pickup, release and collisions audio. Resolves issue #3 

The sounds can be configured per `GrabbableObjectType` as seen below.

Pickup and release sounds sounds are played when an `AVR_Grabbable` grabs/releases an object.

Collision sounds will be played whenever a collision happens, and the volume will be multiplied based on the speed and mass of the object being collided, providing more realistic collision sounds.

Each sound is optional, and the system will work fine if any of them are left null. 

This PR also adds an `AudioListener` component to the main camera on the PlayerRig prefab.

## Please Note
I am not super familiar with the codebase, and I may have broke formatting rules that you used to write it. I couldnt find a file with contributing information, so if I made any mistakes with your projects formatting standard please do let me know and I will fix them!

### CODE REVIEW

**Comment by wmcnamara** [comment]
I have a testing scene that I used to test this on my local branch. If you would like, I can push the testing scene to a different branch on my repository, and then send you a link to that branch. That way you can try the testing scene out yourself if you would like.

Also, it just dawned upon me that I wrote no documentation for this. I took a look through the repo, and couldnt find any markdown files for the documentation. How should I go about documenting this so that the information appears in the page for AVR_Grabbable? Or is it not necessary for this situation. Thanks!

**Comment by Helliaca** [comment]
This works really well, thanks for the good work!

There are a couple of small details I'd like to iron out:

- Most (if not all) arc-vr scripts try to auto pick-up their components if they are not assigned. It would be great if Grabbable did the same with the AudioSource. A simple `source ??= GetComponent<AudioSource>();` in `AVR_Grabbable.Awake` before your if-statement should suffice.

- The documentation is generated based on the `<summary>` comments in the code. I think your comments in `GrabbableObjectType.cs` are enough documentation as it is, but you can add more to Grabbable if you like. 
To re-generate the documentation simply run `.\doxygen_1_8_7.exe .\avr_dxy_config` in the `Packages/com.avr.core/Documentation` folder and let Unity re-import all the html files. (Not sure how you would do this on mac/linux)

- The only real problem I encountered whilst testing was this: The collision sounds work well whilst holding the object, but when I throw it against a wall or the ground (Like bouncing a basketball of mass 1), the sound frequently doesn't play. 
 
For the last point, perhaps I can offer some help:

It appears the objects are reaching terminal velocity, because changing your terminalSpeed to 999.0f fixed it (sort of). 
I do like the approach of using terminal velocity as the limiting factor here, but something seems off with your equation:
For a basketball of mass 1, your terminalSpeed would be = sqrt(2 * 1 * 9.81 / ( 2.0 * 1.1)) = 2.99m/s, which doesn't seem like a lot to me. A quick google search says that a real-life basketball has a terminal velocity of 20m/s.

This made me wonder, why are you multiplying the air density by 2?
Looking at the terminal velocity equation from your source, there is no 2 in the bottom of the fraction:
image
As for the drag coefficient and frontal area, they obviously depend on the object in question, but I would argue that *most* grabbable objects have a frontal area smaller than 1 square meters, so perhaps 0.5 would be an adequate value here?

As for the drag coefficient, based on this (wikipedia):
image
Most coefficients appear to be under 1. I think approximating the "average grabbed object" as a sphere seems reasonable, thus I would go with something like 0.5.

That would roughly lead us to terminalSpeed = sqrt( (2 * mass * 9.81) / (1.1 * 0.5 * 0.5) ) = 8.45m/s. Still not 20, but  closer at least. If I plug these numbers into Grabbable, it only fails to play the sound if I throw the ball really hard.

Either way, this is good stuff. Thanks a lot for contributing!

**Comment by wmcnamara** [comment]
Hello! I've pushed a commit that accounts for drag and frontal area in a very simple way.

I used a ternary operator for the drag, but I know that some people really dislike ternaries so if you would like me to change that to something a bit more readable let me know.

**Comment by Helliaca** [comment]
I don't have anything against ternaries, probably overuse them a lot myself :D

I took the liberty of adding your sound files as defaults to the pre-configured GrabbableObjectTypes. That way they aren't hidden away in some package folder.
I also regenerated the documentation so it includes your new struct and comments.

**Comment by wmcnamara** [comment]
Thank you! I love this project, its very useful for my own games. Im happy I could contribute to it (:

**Pull request merged**
